[package]
name = "ct"
version = "0.1.0"
authors = ["Łukasz Niemier <lukasz@niemier.pl>"]

description = "Constatn time numeric operations in Rust"
license = "MIT"

repository = "https://github.com/hauleth/ct"
